spring:
  application:
    name: @project.name@
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/